import ModeSwitch from './components/ModeSwitch';
import './globals.css';

export const metadata = {
  title: '이현수의 포트폴리오',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const settingModeScript = `
  if (localStorage.theme === 'dark' || (!('theme' in localStorage) 
  && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
    document.documentElement.classList.add('dark')
  } else {
    document.documentElement.classList.remove('dark')
  }
  `;
  return (
    <html lang="en">
      <body className="bg-backgroundColor transition-[background-color]">
        <script dangerouslySetInnerHTML={{ __html: settingModeScript }} />
        <header>
          <ModeSwitch />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
